// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats() {
  return window['go']['service']['AppService']['GetStats']();
}

export function IsWorkActive() {
  return window['go']['service']['AppService']['IsWorkActive']();
}

export function SelectFiles(arg1) {
  return window['go']['service']['AppService']['SelectFiles'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['service']['AppService']['SendRequest'](arg1);
}

export function StopWork() {
  return window['go']['service']['AppService']['StopWork']();
}

export function WaitWork() {
  return window['go']['service']['AppService']['WaitWork']();
}
