// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToBookmark(arg1, arg2) {
  return window['go']['service']['AppService']['AddToBookmark'](arg1, arg2);
}

export function DeleteBookmarks(arg1) {
  return window['go']['service']['AppService']['DeleteBookmarks'](arg1);
}

export function GetAllBookmarks(arg1, arg2, arg3, arg4) {
  return window['go']['service']['AppService']['GetAllBookmarks'](arg1, arg2, arg3, arg4);
}

export function GetAllTags() {
  return window['go']['service']['AppService']['GetAllTags']();
}

export function GetBookmarkByID(arg1) {
  return window['go']['service']['AppService']['GetBookmarkByID'](arg1);
}

export function GetCurrentRequest() {
  return window['go']['service']['AppService']['GetCurrentRequest']();
}

export function GetStats() {
  return window['go']['service']['AppService']['GetStats']();
}

export function IsWorkActive() {
  return window['go']['service']['AppService']['IsWorkActive']();
}

export function ResetCurrentRequest() {
  return window['go']['service']['AppService']['ResetCurrentRequest']();
}

export function SelectFiles(arg1) {
  return window['go']['service']['AppService']['SelectFiles'](arg1);
}

export function SetCurrentRequest(arg1) {
  return window['go']['service']['AppService']['SetCurrentRequest'](arg1);
}

export function StartCurrentRequest() {
  return window['go']['service']['AppService']['StartCurrentRequest']();
}

export function StopWork() {
  return window['go']['service']['AppService']['StopWork']();
}

export function WaitWork() {
  return window['go']['service']['AppService']['WaitWork']();
}
