// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddToBookmark(arg1:string,arg2:Array<string>):Promise<void>;

export function GetAllBookmarks(arg1:string,arg2:string,arg3:number,arg4:number):Promise<models.BookmarkList>;

export function GetAllTags():Promise<Array<string>>;

export function GetCurrentRequest():Promise<models.Data>;

export function GetStats():Promise<models.Stat>;

export function IsWorkActive():Promise<boolean>;

export function ResetCurrentRequest():Promise<void>;

export function SelectFiles(arg1:boolean):Promise<Array<string>>;

export function SetCurrentRequest(arg1:models.Data):Promise<void>;

export function StartCurrentRequest():Promise<void>;

export function StopWork():Promise<void>;

export function WaitWork():Promise<void>;
