// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetCurrentRequest():Promise<domain.Data>;

export function GetStats():Promise<domain.Stat>;

export function IsWorkActive():Promise<boolean>;

export function ResetCurrentRequest():Promise<void>;

export function SelectFiles(arg1:boolean):Promise<Array<string>>;

export function SetCurrentRequest(arg1:domain.Data):Promise<void>;

export function StartCurrentRequest():Promise<void>;

export function StopWork():Promise<void>;

export function WaitWork():Promise<void>;
